# Generated by Django 3.2.16 on 2023-02-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is the test description for my project'),
            preserve_default=False,
        ),
    ]
